apiVersion: v1
kind: Service
metadata:
  name: ser6
spec:
  selector:
    app: jenkpod
  ports:
    - name: tomport
      protocol: TCP
      port: 80
      targetPort: 8080
  externalIPs: 
    - 172.31.26.114    
