apiVersion: v1
kind: Service
metadata:
  name: serv2
spec:
  selector:
    app: japp1
  type: NodePort
  ports:
    - name: jport
      protocol: TCP
      port: 8002
      targetPort: 8080
      nodePort: 30000
