apiVersion: v1
kind: Service
metadata:
  name: serv8
spec:
  selector:
    app: jenkpod1
  ports:
    - name: jport
      protocol: TCP
      port: 8005
      targetPort: 8080
    - name: jporthost
      protocol: TCP
      port: 50000
      targetPort: 50000
  externalIPs: 
    - 172.31.26.114    
