apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhostdp1
  labels:
    app: jenkapp1
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: jenkpod1
  template:
    metadata:
      labels:
        app: jenkpod1
    spec:  
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
      tolerations:
        - key: "color"
          operator: "Equal"
          value: "blue"
          effect: "NoSchedule"
